### PR TITLE
Update batchupload.md

### PR DESCRIPTION
**Pull request by klj0019**
**Before spectrum upload users are instructed to:**
" After the batch file has been completed please send the batch and MS data to Morgan (ccms-web@cs.ucsd.edu)."

**Swapped Ming for Morgan as the new facilitator. Waiting to change email at a future date.** 

"  Addendum: Access to workflow is restricted - To request access please email Ming (ccms-web@cs.ucsd.edu)"

"To contribute this library to the public GNPS library, please email Ming (ccms-web@cs.ucsd.edu)"

### CODE REVIEW

**Comment by mwang87** [comment]
Can you please correct it and remove the link to the workflow. Users will have to submit the batch file along with spectrum files directly to Morgan as she will be the only person able to run the batch workflow.

**Comment by klj0019** [comment]
Made changes to the workflow. 

1. Upload an empty mgf file to GNPS so that it appears in the file selector directory
2. Export excel file as a tab separated text file and upload to GNPS (recommended export from Windows office 2013 or newer. Verify that line endings are UNIX and not Windows line endings)
3. Users will then need to contact Morgan (ccms-web@cs.ucsd.edu) and send her the batch and spectrum files.
4. To contribute this library to the public GNPS library, please email Morgan (ccms-web@cs.ucsd.edu), listing the location of the library and the public library it should be added to for approval.

**Comment by mwang87** [comment]
The updated process does not require an empty mgf file. That will be removed. The process will be as follows:

1. Create batch file according docs
2. Validate batch file
3. Send over mzML and batch to Morgan
4. Provide library description
5. Provide library name
6. Validate selected MS2 spectra
7. Check its public/live

**Comment by klj0019** [comment]
Documentation Updated

**Comment by mwang87** [comment]
Merged!.

**Pull request merged**
