### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by amcaraballor**
Include link and visualization of GNPS/MassIVE uptime monitoring

### CODE REVIEW

**Comment by lfnothias** [comment]
Nice !

**Comment by mwang87** [comment]
Does this actually work inside of markdown, at least previewing here it does not.

**Comment by amcaraballor** [comment]
I included it in the Index but the box is not actually there, just the link for the uptime visualization...

**Comment by mwang87** [comment]
The link is fine, but there is an iframe, if that doesn't work please remove extraneous code.

**Pull request closed without merging**
