### PR TITLE
Merge pull request #1 from CCMS-UCSD/master

### PR DESCRIPTION
**Pull request by mabelgon88**
Sychronize from CCMS

### CODE REVIEW

**Comment by mwang87** [comment]
Any updates @mabelgon88?

**Comment by mabelgon88** [comment]
Hi @mwang87. Sorry that I just replied now. I was on a field trip in Colombia, but now I´m back here. I was trying to use the superquick start guide, but I have realized that I haven´t files with the size required for using this superquick tool. I tried the tool using the first four files of this MASSIVE dataset ftp://massive.ucsd.edu/MSV000084479/peak/mzXML/, but an exception report is appearing after clicking on the Analize button. I don´t know if this bug is related with the type of data that I am using.

**Comment by mwang87** [comment]
Thanks @mabelgon88 Can we look at it this afternoon really quickly? It might be an issue with the explanation in the documentation.

**Comment by mwang87** [comment]
How is this PR going?

**Comment by mabelgon88** [comment]
Hi Ming. I finally have been able to use the superquick start guide. I have included a checklist for facilitating the verification process of the files in this: https://github.com/CCMS-UCSD/GNPSDocumentation

**Comment by mwang87** [comment]
Closing due to inactivity.

**Pull request closed without merging**
