### PR TITLE
GC-MS library search/MS-DIAL page update April 2020

### PR DESCRIPTION
**Pull request by MelissaESPOSITO**

### CODE REVIEW

**Comment by MelissaESPOSITO** [comment]
@mwang87 
Here is the GC-MS-library-search page updated to conform with the job page, the MS-DIAL page updated, I removed the last part so now, it's a workflow for pre-processing and to use GNPS library search. I added also new documentation about doing pre-processing with MZmine2 with GC-MS data. 
It is ready to merge.

**Comment by MelissaESPOSITO** [comment]
I added the citation

**Comment by mwang87** [comment]
Thanks will review and give feedback! Thanks @MelissaESPOSITO

**Comment by MelissaESPOSITO** [comment]
@mwang87 
Louis added some modifications on those pages and I added citations also.
It is ready to merge.
thanks

**Pull request merged**
