### PR TITLE
GC molecular networking documentation

### PR DESCRIPTION
**Pull request by MelissaESPOSITO**

### CODE REVIEW

**Comment by mwang87** [comment]
I think there are a few missing images, will you be uploading those now or later?

**Comment by MelissaESPOSITO** [comment]
I'll do it now

**Comment by MelissaESPOSITO** [comment]
it should be ok now, let me know if you still have issues with pictures.

**Comment by MelissaESPOSITO** [comment]
ready for merge

**Comment by mwang87** [comment]
The images should refer to within this repository rather than google links as those will likely expire.

**Comment by MelissaESPOSITO** [comment]
Yes, I changed that last Friday. It should be in the last version. I'll check tomorrow and give you the name of the file.Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Ming Wang <notifications@github.com> Date : 07/10/2019  17:35  (GMT-08:00) À : CCMS-UCSD/GNPSDocumentation <GNPSDocumentation@noreply.github.com> Cc : MelissaESPOSITO <melissa.esposito44@gmail.com>, Author <author@noreply.github.com> Objet : Re: [CCMS-UCSD/GNPSDocumentation] GC molecular networking documentation (#95) The images should refer to within this repository rather than google links as those will likely expire.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/CCMS-UCSD/GNPSDocumentation/pull/95?email_source=notifications\u0026email_token=AKN3UTXXIRFKDGKMHM2TZ5TQNPIVFA5CNFSM4I5SUDQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEASH3WY#issuecomment-539262427",
"url": "https://github.com/CCMS-UCSD/GNPSDocumentation/pull/95?email_source=notifications\u0026email_token=AKN3UTXXIRFKDGKMHM2TZ5TQNPIVFA5CNFSM4I5SUDQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEASH3WY#issuecomment-539262427",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by MelissaESPOSITO** [comment]
GC-MS_MN_GNPS-documentation.md has the figures in this repository. So it should be ready to merge.

**Comment by mwang87** [comment]
Thanks Melissa, it seems that several of the pages are repeated 4 times. The pages don't actual seem any different, did we actually need multiple?

**Comment by MelissaESPOSITO** [comment]
no, I don't know why we have multiples, maybe I did something wrong. One is enough!

**Comment by mwang87** [comment]
Yeah it seems there are 4 files. can you remove the all the extra ones before we merge? Thanks!

**Comment by MelissaESPOSITO** [comment]
Is it ok now? sorry about that.

**Comment by mwang87** [comment]
Looks great! checking in.

**Comment by MelissaESPOSITO** [comment]
Is it ok now? Sorry about that.

**Pull request merged**
